spring :
  profiles :
    active : dev

server:
  port : 8095

camel:
  springboot:
    shutdownTimeout : 2
    health.indicator.enabled: true

management:
  security:
    enable: false

---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: modi094237
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailsender1256@gmail.com
    password: modi094237
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true
    mailTo: mailsender1256@gmail.com
    mailFrom: mailsender1256@gmail.com
  camel:
      external :
        properties :
          inputFile : file:data/input?delete=true&readLock=none&moveFailed=error
          outputFile : file:data/output
          timerTime: timer:hello?period=10s
          jdbcDataSource: jdbc:dataSource
          successRoute: file:data/output?fileName=Success.txt
          healthRoute: timer:healthRoute?period=10s
          healthEndpoint:     http://localhost:8095/health


message: DEV ENV


---
spring:
  profiles: mock
  camel:
      external :
        properties :
          inputFile : file:data/input?delete=true&readLock=none
          outputFile : mock:output
          timerTime: direct:input
          jdbcDataSource: mock:output1
          successRoute: mock:output2
  mail:
      host: smtp.gmail.com
      port: 587
      username: mailsender1256@gmail.com
      password: modi094237
      properties.mail.smtp.auth:  true
      properties.mail.smtp.starttls.enable: true
      mailTo: mailsender1256@gmail.com
      mailFrom: mailsender1256@gmail.com

message: DEV ENV


---
spring:
  profiles: stage
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/localDB
      username: postgres
      password: modi094237
  mail:
      host: smtp.gmail.com
      port: 587
      username: mailsender1256@gmail.com
      password: modi094237
      properties.mail.smtp.auth:  true
      properties.mail.smtp.starttls.enable: true
      mailTo: mailsender1256@gmail.com
      mailFrom: mailsender1256@gmail.com


  camel:
      external :
        properties :
          inputFile : file:data/input?delete=true&readLock=none&moveFailed=error
          outputFile : file:data/output
          timerTime: timer:hello?period=10s
          jdbcDataSource: jdbc:dataSource
          successRoute: file:data/output?fileName=Success.txt

message: STAGE ENV
---

spring:
  profiles: prod
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/localDB
      username: postgres
      password: modi094237
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailsender1256@gmail.com
    password: modi094237
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true
    mailTo: mailsender1256@gmail.com
    mailFrom: mailsender1256@gmail.com


  camel:
      external :
        properties :
          inputFile : file:data/input?delete=true&readLock=none&moveFailed=error
          outputFile : file:data/output
          timerTime: timer:hello?period=10s
          jdbcDataSource: jdbc:dataSource
          successRoute: file:data/output?fileName=Success.txt
message: PROD ENV