spring :
  profiles :
    active : dev
server.port : 8094
camel.springboot.shutdownTimeout : 2
---
spring:
  profiles: dev
  camel:
      external :
        properties :
          inputFile : file:data/input?delete=true&readLock=none
          outputFile : file:data/output
          timerTime: timer:hello?period=10s
message: DEV ENV


---
spring:
  profiles: mock
  camel:
      external :
        properties :
          inputFile : file:data/input?delete=true&readLock=none
          outputFile : mock:output
          timerTime: direct:input
message: DEV ENV


---
spring:
  profiles: stage
  camel:
        external :
          properties :
            inputFile : file:data/input?delete=true&readLock=none
            outputFile : file:data/stage/output
            timerTime: timer:hello?period=10s

message: STAGE ENV
---

spring:
  profiles: prod
  camel:
        external :
          properties :
            inputFile : file:data/input?delete=true&readLock=none
            outputFile : file:data/prod/output
            timerTime: timer:hello?period=10s
message: PROD ENV