CREATE TABLE ITEMS(
ITEM_I SERIAL,
SKU_NUMBER TEXT NOT NULL,
ITEM_DESCRIPTION TEXT DEFAULT NULL,
PRICE NUMERIC(5,2),
CREATE_TIMESTAMP TIMESTAMPTZ NULL DEFAULT current_timestamp
);

select * from ITEMS;